# Generated by Django 4.0.5 on 2022-06-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='projects',
        ),
    ]
